pipeline:
  test:
    image: node:7
    commands:
      - npm install -g phantomjs-prebuilt
      - npm install
      - node_modules/ember-cli/bin/ember test
  # build:
  #   image: node:7
  #   commands:
  #     - npm install
  #     - node_modules/ember-cli/bin/ember build --environment="production"
